spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/timebank
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      connection-timeout: 20000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

  cache:
    jcache:
      config: classpath:ehcache.xml

jwt:
  secret: ${JWT_SECRET:your-256-bit-secret-key-for-jwt-token-generation-and-validation}
  expiration: 86400000 # 24 hours

server:
  port: 8080
  servlet:
    context-path: /api
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/plain
    min-response-size: 1024

websocket:
  endpoint: /ws
  allowed-origins: http://localhost:5173

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.timebank: DEBUG